argument: argument.c
	gcc argument.c -lpthread -o argument

beer: beer.c
	gcc beer.c -lpthread -o beer

param_test: param_test.c
	gcc param_test.c -lpthread -o param_test

beer_fixed_strategy_2: beer_fixed_strategy_2.c
	gcc beer_fixed_strategy_2.c -lpthread -o beer_fixed_strategy_2
