advice_server: advice_server.c
	gcc -I../my_header_files advice_server.c \
	      ../my_object_files/error.o -o advice_server

ikkp_server: ikkp_server.c
	gcc -I../my_header_files ikkp_server.c \
        ../my_object_files/error.o \
        ../my_object_files/catch.o -o ikkp_server
